[SFEQS-686] Scaffold io-functions-sign repository
pagopa/io-functions-sign pull request #1
Opened 2022-04-19 10:09 UTC by lucacavallaro

2022-04-20 16:23 UTC, gunzip requested changes

2022-04-20 16:23 UTC, gunzip commented on .eslintrc.json
> +    "functional/immutable-data": "off"
why off?

2022-04-20 16:23 UTC, gunzip commented on .gitignore
> +node_modules
I'd add at least 

```
.env*

*.js
!jest.config.js
!.eslintrc.js

```

2022-04-20 16:23 UTC, gunzip commented on .node-version
> +16.13.0
does this match the deployed function runtime version?

2022-04-20 16:23 UTC, gunzip commented on docs/openapi.yaml
> +          description: Il profilo del Signer
should be in english see https://github.com/pagopa/io-functions-services/blob/master/openapi/index.yaml

2022-04-20 16:23 UTC, gunzip commented on host.json
> +  "extensionBundle": {
we usually prefer to control packages version though csjprog

https://github.com/pagopa/io-functions-services/blob/master/extensions.csproj

2022-04-20 16:25 UTC, lucacavallaro commented on .node-version
> +16.13.0
yes

2022-04-22 10:33 UTC, gunzip approved these changes

2022-04-22 12:31 UTC, merged